name: library

services:
  library-db:
    image: postgres:17.5-bookworm
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - library-db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - library

volumes:
  library-db:
    name: library-db

networks:
  library:
    name: library
